### PR TITLE
Fix import in functional tests

### PR DESCRIPTION
**Pull request by r-f-g**
- fix import after moving find_units and find_units_on_machine to utils

fixes: https://bugs.launchpad.net/juju-verify/+bug/1951951

### CODE REVIEW

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by auria — DISMISSED** [review]
+1

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by auria — APPROVED** [review]
LGTM, thanks

**Pull request merged**
