### PR TITLE
Adapt to changes in libjuju3 and zaza

### PR DESCRIPTION
**Pull request by mkalcok**
These changes reflect changes that were made to juju library and zaza framework.

- `juju.Action` object has simplified access to action results via `results` attribute and no longer needs to search `self.data`. This change makes our helper function `data_from_action` likely obsolete and we should phase it out.
- `zaza.run()` function was removed, and although it was later re-added with slightly different functionality, I think that we can use the alternative `sync_wrapper` method.

### CODE REVIEW

**Review by rgildein — APPROVED** [review]
LGTM

**Review by rgildein — COMMENTED** [review]
recheck-full

**Review by rgildein — COMMENTED** [review]
recheck-full

**Review by rgildein — COMMENTED** [review]
recheck-full

**Comment by mkalcok** [comment]
replaced by #74

**Pull request closed without merging**
