### PR TITLE
Add pre-commit

### PR DESCRIPTION
**Pull request by rgildein**
- drop pylint and mypy
- add pre-commit
- applied pre-commit

### CODE REVIEW

**Review by Pjack — DISMISSED** [review]
LGTM,  Just a quick question.
Any different between the svg chart? I cannot distinguish them

**Comment by rgildein** [comment]
> LGTM, Just a quick question. Any different between the svg chart? I cannot distinguish them

I checked and there was no change in how they look.

**Comment by mkalcok** [comment]
Couple questions.

- What's the reason for entirely dropping pylint and mypy?
- Shouldn't there be pre-commit config file to tell pre-commit what to do?

**Comment by rgildein** [comment]
> Couple questions.
> 
>     * What's the reason for entirely dropping pylint and mypy?

We are using `pflake8`, `black` and `isort` in all projects in BootStack and I think that we should use same tools here. Additional tools are no needed. 

> 
>     * Shouldn't there be pre-commit config file to tell pre-commit what to do?

Yes, I forgot to add it. Thanks

**Comment by mkalcok** [comment]
> We are using pflake8, black and isort in all projects in BootStack and I think that we should use same tools here. Additional tools are no needed.

I'm sad about this...pylint is much more comprehensive than flake8...regarding the mypy, bootstack charms don't use typehinting because they often have to be supported on older python...I think we should consider keeping at least mypy to enforce typhinting since we can afford to support it.

**Review by Pjack — DISMISSED** [review]

**Review by mkalcok — DISMISSED** [review]
LGTM, thanks.

**Review by rgildein — COMMENTED** [review]
recheck

**Review by Pjack — APPROVED** [review]

**Review by mkalcok — APPROVED** [review]

**Pull request merged**
