### PR TITLE
Neutron actions with param

### PR DESCRIPTION
**Pull request by mkalcok**

### CODE REVIEW

**Comment by r-f-g** [comment]
I'm not sure why the Ceph cluster is not healthy, but maybe we can try to use `_wait_to_healthy_ceph_cluster` in `SetUp` function.

**Comment by mkalcok** [comment]
The strange thing is, this change does not have anything to do with `ceph`...so why are those func tests suddenly, and consistently failing in this PR?

**Comment by r-f-g** [comment]
> The strange thing is, this change does not have anything to do with `ceph`...so why are those func tests suddenly, and consistently failing in this PR?

I'm not sure. We need to check the model in CI Serverstack. @auria

**Comment by mkalcok** [comment]
Just to add some info. I tried to run tests manually in my env (serverstack) and it took 10mins to deploy model and start tests

**Review by r-f-g — APPROVED** [review]
LGTM

**Pull request merged**
