### PR TITLE
Fix check_quorum for Ceph Mon charm

### PR DESCRIPTION
**Pull request by r-f-g**
- replace all custom ceph-mon charm w/ openstack-charmers-next
 - add function to parse new action output

fixes: [#1945113](https://bugs.launchpad.net/juju-verify/+bug/1945113)

### CODE REVIEW

**Review by auria — APPROVED** [review]
LGTM. Please update the commit message (typo on `Fix check_quorum`).

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by auria — APPROVED** [review]
LGTM

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by auria — APPROVED** [review]
+1

**Pull request merged**
