### PR TITLE
Adapt to changes in libjuju3 and zaza

### PR DESCRIPTION
**Pull request by mkalcok**
These changes reflect changes that were made to juju library and zaza framework.

- `juju.Action` object has simplified access to action results via `results` attribute and no longer needs to search `self.data`. This change makes our helper function `data_from_action` likely obsolete and we should phase it out.
- `zaza.run()` function was removed, and although it was later re-added with slightly different functionality, I think that we can use the alternative `sync_wrapper` method.

### CODE REVIEW

**Review by rgildein — COMMENTED** [review]
recheck-full

**Review by Pjack — APPROVED** [review]
LGTM

**Review by rgildein — COMMENTED** [review]
recheck-full

**Comment by rgildein** [comment]
Hi @mkalcok, Can you check why functional tests are failing. Thanks

**Comment by mkalcok** [comment]
> Hi @mkalcok, Can you check why functional tests are failing. Thanks

functional tests for `ceph` timed out while deploying model. `ceph-mon` and `ceph-osd` applications did not reach active/idle status. I'll try to run it locally to see what's wrong

**Comment by rgildein** [comment]
I believe that this is blocked by #80.

**Comment by mkalcok** [comment]
Both [libjuju](https://github.com/juju/python-libjuju/issues/705) and [zaza](https://github.com/openstack-charmers/zaza/pull/571) were made backward compatible. These changes are no longer needed.

**Pull request closed without merging**
