### PR TITLE
[CI] wait for last run to finished

### PR DESCRIPTION
**Pull request by r-f-g**
- add 10s wait if last workflow run is not completed
- skip tests only if last run was completed

### CODE REVIEW

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by mkalcok — APPROVED** [review]

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by r-f-g — COMMENTED** [review]
recheck-snap

**Review by r-f-g — COMMENTED** [review]
recheck-full

**Review by auria — APPROVED** [review]
+1

**Review by mkalcok — APPROVED** [review]

**Review by auria — APPROVED** [review]
We discussed about the javascript recursion limit which shouldn't happen considering tests can't run more for more than 6h and calls happen every 10s. If such limit would be hit, sleep delay could be increased or the code logic be converted to iter (rather than recursion).

+1 from me.

**Pull request merged**
